=begin
#kabuステーションAPI

## 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)

The version of the OpenAPI document: 1.5

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for KabustationClient::OrderApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrderApi' do
  before do
    # run before each test
    @api_instance = KabustationClient::OrderApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrderApi' do
    it 'should create an instance of OrderApi' do
      expect(@api_instance).to be_instance_of(KabustationClient::OrderApi)
    end
  end

  # unit tests for cancelorder_put
  # 注文取消
  # 注文を取消します
  # @param x_api_key トークン発行メソッドで取得した文字列
  # @param request_cancel_order 
  # @param [Hash] opts the optional parameters
  # @return [OrderSuccess]
  describe 'cancelorder_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for sendoder_future_post
  # 注文発注（先物）
  # 先物銘柄の注文を発注します。&lt;br&gt; 同一の銘柄に対しての注文は同時に5件ほどを上限としてご利用ください。
  # @param x_api_key トークン発行メソッドで取得した文字列
  # @param request_send_order_deriv_future 
  # @param [Hash] opts the optional parameters
  # @return [OrderSuccess]
  describe 'sendoder_future_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for sendorder_option_post
  # 注文発注（オプション）
  # オプション銘柄の注文を発注します。&lt;br&gt; 同一の銘柄に対しての注文は同時に5件ほどを上限としてご利用ください。
  # @param x_api_key トークン発行メソッドで取得した文字列
  # @param request_send_order_deriv_option 
  # @param [Hash] opts the optional parameters
  # @return [OrderSuccess]
  describe 'sendorder_option_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for sendorder_post
  # 注文発注（現物・信用）
  # 注文を発注します。&lt;br&gt; 同一の銘柄に対しての注文は同時に5件ほどを上限としてご利用ください。
  # @param x_api_key トークン発行メソッドで取得した文字列
  # @param request_send_order 
  # @param [Hash] opts the optional parameters
  # @return [OrderSuccess]
  describe 'sendorder_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
