=begin
#kabuステーションAPI

## 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)

The version of the OpenAPI document: 1.5

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KabustationClient::WalletCashSuccess
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KabustationClient::WalletCashSuccess do
  let(:instance) { KabustationClient::WalletCashSuccess.new }

  describe 'test an instance of WalletCashSuccess' do
    it 'should create an instance of WalletCashSuccess' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(KabustationClient::WalletCashSuccess)
    end
  end

  describe 'test attribute "stock_account_wallet"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "au_kc_stock_account_wallet"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "au_jbn_stock_account_wallet"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
