=begin
#kabuステーションAPI

## 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)

The version of the OpenAPI document: 1.5

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

# Common files
require 'kabustation_client/api_client'
require 'kabustation_client/api_error'
require 'kabustation_client/version'
require 'kabustation_client/configuration'

# Models
require 'kabustation_client/models/api_soft_limit_response'
require 'kabustation_client/models/board_success'
require 'kabustation_client/models/board_success_buy1'
require 'kabustation_client/models/board_success_buy10'
require 'kabustation_client/models/board_success_buy2'
require 'kabustation_client/models/board_success_buy3'
require 'kabustation_client/models/board_success_buy4'
require 'kabustation_client/models/board_success_buy5'
require 'kabustation_client/models/board_success_buy6'
require 'kabustation_client/models/board_success_buy7'
require 'kabustation_client/models/board_success_buy8'
require 'kabustation_client/models/board_success_buy9'
require 'kabustation_client/models/board_success_sell1'
require 'kabustation_client/models/board_success_sell10'
require 'kabustation_client/models/board_success_sell2'
require 'kabustation_client/models/board_success_sell3'
require 'kabustation_client/models/board_success_sell4'
require 'kabustation_client/models/board_success_sell5'
require 'kabustation_client/models/board_success_sell6'
require 'kabustation_client/models/board_success_sell7'
require 'kabustation_client/models/board_success_sell8'
require 'kabustation_client/models/board_success_sell9'
require 'kabustation_client/models/error_response'
require 'kabustation_client/models/exchange_response'
require 'kabustation_client/models/margin_premium_response'
require 'kabustation_client/models/margin_premium_response_day_trade'
require 'kabustation_client/models/margin_premium_response_general_margin'
require 'kabustation_client/models/order_success'
require 'kabustation_client/models/orders_success'
require 'kabustation_client/models/orders_success_details_inner'
require 'kabustation_client/models/positions'
require 'kabustation_client/models/positions_deriv'
require 'kabustation_client/models/positions_success'
require 'kabustation_client/models/primary_exchange_response'
require 'kabustation_client/models/ranking_by_category_response'
require 'kabustation_client/models/ranking_by_category_response_ranking_inner'
require 'kabustation_client/models/ranking_by_margin_response'
require 'kabustation_client/models/ranking_by_margin_response_ranking_inner'
require 'kabustation_client/models/ranking_by_tick_count_response'
require 'kabustation_client/models/ranking_by_tick_count_response_ranking_inner'
require 'kabustation_client/models/ranking_by_trade_value_response'
require 'kabustation_client/models/ranking_by_trade_value_response_ranking_inner'
require 'kabustation_client/models/ranking_by_trade_volume_response'
require 'kabustation_client/models/ranking_by_trade_volume_response_ranking_inner'
require 'kabustation_client/models/ranking_default_response'
require 'kabustation_client/models/ranking_default_response_ranking_inner'
require 'kabustation_client/models/ranking_get200_response'
require 'kabustation_client/models/regist_success'
require 'kabustation_client/models/regulations_response'
require 'kabustation_client/models/regulations_response_regulations_info_inner'
require 'kabustation_client/models/request_cancel_order'
require 'kabustation_client/models/request_register'
require 'kabustation_client/models/request_register_symbols_inner'
require 'kabustation_client/models/request_send_order'
require 'kabustation_client/models/request_send_order_deriv_future'
require 'kabustation_client/models/request_send_order_deriv_future_reverse_limit_order'
require 'kabustation_client/models/request_send_order_deriv_option'
require 'kabustation_client/models/request_send_order_reverse_limit_order'
require 'kabustation_client/models/request_token'
require 'kabustation_client/models/request_unregister'
require 'kabustation_client/models/symbol_name_success'
require 'kabustation_client/models/symbol_success'
require 'kabustation_client/models/token_success'
require 'kabustation_client/models/unregister_all_success'
require 'kabustation_client/models/wallet_cash_success'
require 'kabustation_client/models/wallet_future_success'
require 'kabustation_client/models/wallet_margin_success'
require 'kabustation_client/models/wallet_option_success'

# APIs
require 'kabustation_client/api/auth_api'
require 'kabustation_client/api/info_api'
require 'kabustation_client/api/order_api'
require 'kabustation_client/api/register_api'
require 'kabustation_client/api/wallet_api'

# WebSocket
require 'kabustation_client/push_client'

module KabustationClient
  class << self
    # Customize default settings for the SDK using block.
    #   KabustationClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
